---
- include:              '../tasks/install_files.yml'
- include:              '../tasks/lines_in_files.yml'
- include:              '../tasks/commands.yml'
  when:                 install_files_result.changed or lines_in_files_result.changed

